app.py
from flask import Flask, render_template
from routes.download_mp3 import download_mp3_bp
from routes.index import index_bp

app = Flask(__name__)

app.register_blueprint(download_mp3_bp, url_prefix='/mp3')
app.register_blueprint(index_bp, url_prefix='/')

if __name__ == '__main__':
	app.run(host='0.0.0.0', port=8080)

routes/download_mp3.py
# download_mp3.py
from flask import Blueprint, request, send_file
from pytube import YouTube
from moviepy.editor import VideoFileClip
import time
import os
import logging
from utils.sanitize_filename import sanitize_filename

download_mp3_bp = Blueprint('download_mp3', __name__)

@download_mp3_bp.route('/download', methods=['POST'])
def download_mp3():
  try:

    video_url = request.form['video_url']

    yt = YouTube(video_url)

    video_title = yt.title

    stream = yt.streams.filter(only_audio=True).first()

    timestamp = int(time.time())

    filename_with_timestamp = sanitize_filename(f'{ video_title }_{ timestamp }.mp3')
    
    mp3_path = os.path.join('tmp/mp3', filename_with_timestamp)

    stream.download(output_path='tmp/mp3', filename = filename_with_timestamp)

    file_name_to_download = f'{ sanitize_filename(video_title) }.mp3'

    response = send_file(mp3_path, as_attachment=True, download_name = file_name_to_download)

    os.remove(mp3_path)

    return response

  except Exception as e:
      return str(e)

routes/index.py
# index.py
from flask import Blueprint, request, send_file, render_template
import os
import logging

index_bp = Blueprint('index', __name__)

@index_bp.route('')
def index():
  logging.info('asdas')
  return render_template("index.html")

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>YTD - Clean and fast download</title>
  <link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
</head>

<body>

  <header class="bg-cyan-500 p-4">
    <h2 class="text-3xl text-center font-light text-white m-0">YTD - Clean and fast download</h2>
  </header>
  
  <div class="w-full flex justify-center p-8">
    <main class="max-w-3xl w-full flex border">
  
      <form class="w-full flex" action="{{ url_for('download_mp3.download_mp3') }}" method="POST">
        <input type="text" name="video_url" placeholder="Enter URL to download" class="border-2 border-gray-700 w-4/5 py-3 px-4"></input>
        <button class="w-1/5 bg-blue-700 text-xl hover:bg-blue-500 text-white py-2 px-3">Download</button>
      </form>
  
    </main>
  </div>


</body>

</html>